name: CI/CD Django Docker

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/bookstore-app
      TAG: latest   # ya ${{ github.sha }} agar unique tag chahiye

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.TAG }} -t ${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker image
      run: |
        docker push ${{ env.IMAGE_NAME }}:${{ env.TAG }}
        docker push ${{ env.IMAGE_NAME }}:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop bookstore || true
          docker rm bookstore || true
          docker pull ${{ env.IMAGE_NAME }}:latest
          docker run -d --name bookstore -p 80:8000 ${{ env.IMAGE_NAME }}:latest
