name: CI/CD Django Docker

on:
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${ { secrets.DOCKER_HUB_USERNAME } }/bookstore-app
      TAG: ${{ github.sha }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build image
      run: docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$TAG .

    - name: Push image
      run: |
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$TAG

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker stop bookstore || true
          docker rm bookstore || true
          docker pull $IMAGE_NAME:latest
          docker run -d --name bookstore -p 80:8000 $IMAGE_NAME:latest
