name: Build, Push and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t bookstore:latest .

      - name: Push Docker image to DockerHub
        run: |
          docker tag bookstore:latest ${{ secrets.DOCKER_USERNAME }}/bookstore:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/bookstore:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/bookstore:latest
            docker stop bookstore || true
            docker rm bookstore || true
            docker run -d -p 8000:8000 --name bookstore ${{ secrets.DOCKER_USERNAME }}/bookstore:latest
